# Generated by Django 3.0.1 on 2019-12-30 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20191230_1531'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'Set a book as returned'),), 'verbose_name': 'Экземпляр', 'verbose_name_plural': 'Экземпляры'},
        ),
    ]
